pipeline:
  name: pl_auto_pipeline_KgA4W
  identifier: pl_auto_pipeline_KgA4W
  projectIdentifier: CDCNGAuto_TriggerProjpMwcrtsszu
  orgIdentifier: CDCNGAuto_TriggerOrgAutod0WQ7OpjFr
  tags: { }
  stages:
      - stage:
          name: s1
          identifier: s1
          description: ""
          type: Custom
          spec:
            execution:
              steps:
                - step:
                    type: Http
                    name: Http_1
                    identifier: Http_1
                    timeout: 10s
                    spec:
                      url: https://qa.harness.io/gateway/pipeline/api/webhook/custom/2WEyqewSRoawecIN89ciYw/v3?accountIdentifier=rXUXvbFqRr2XwcjBu3Oq-Q&orgIdentifier=CDCNGAuto_TriggerOrgAutod0WQ7OpjFr&projectIdentifier=CDCNGAuto_TriggerProjpMwcrtsszu&pipelineIdentifier=pl_auto_pipeline_u4BLC&triggerIdentifier=CDCNGAuto_Custom_Webhook_Trigger_2H1AfsXewf
                      method: POST
                      headers: [ ]
                      inputVariables: [ ]
                      outputVariables: [ ]
                      requestBody: "{\"sample_key\": \"sample_value\"}"
          tags: { }
